### ISSUE TITLE
Add the ability to upload a .vim color file and edit it

### ISSUE THREAD

**Issue by TylerBrabham** [mserdarsanli/VimArtisan#1]
I've used vimartisan to create a few color schemes. It would be nice to be able to modify them later by uploading them to the site.

Thanks for the cool site!

**Comment by mserdarsanli** [comment]
I'm glad you found the site useful.

One simple option is to parse `hi` commands in the uploaded file and generate a base colorscheme with it.
This option would support colorschemes generated by VimArtisan. Though it won't be able to
support colorschemes that are
- Extending another colorscheme by sourcing them first and adding new rules.
- Doing conditional stuff like [Solarized Theme](https://github.com/altercation/ethanschoonover.com/blob/master/projects/solarized/vim-colors-solarized/colors/solarized.vim) which have light and dark options.

etc.

The other options would be slightly more complex. I think it is still worthwhile to at least support files generated with VimArtisan.

**Comment by mserdarsanli** [comment]
#3 should add basic support for this. Keeping the bug open as I've not deployed that to site yet, and there are some minor issues.

**Comment by TylerBrabham** [comment]
Cool. Thanks for working on it. Looking forward to trying it out.

**Comment by mserdarsanli** [comment]
It is now live at https://mserdarsanli.github.io/VimArtisan/

It is now able to load simple colorschemes and colorschemes produces by VimArtisan.

Please let me know if there are any issues and thanks for the suggestion.
